import Foundation

/// A point-in-time snapshot of the user's cognitive state.
/// Generated by the CognitiveModel using health data, time of day, task history, and self-reports.
public struct CognitiveSnapshot: Identifiable, Codable, Sendable {
    public var id: String
    public var energy: EnergyLevel
    public var energyScore: Double          // 0.0 - 1.0
    public var stressScore: Double          // 0.0 - 1.0
    public var focusCapacity: Double        // 0.0 - 1.0
    public var recoveryScore: Double        // 0.0 - 1.0
    public var sleepDebtHours: Double       // accumulated sleep debt
    public var availableMinutes: Int        // estimated free time remaining today
    public var contextNotes: String         // AI-generated context description
    public var executiveFunctionScore: Int  // 0-100, holistic EF score
    public var recommendedTaskDifficulty: TaskDifficulty
    public var timestamp: Date
    public var userId: String
    
    public init(
        id: String = UUID().uuidString,
        energy: EnergyLevel = .moderate,
        energyScore: Double = 0.5,
        stressScore: Double = 0.3,
        focusCapacity: Double = 0.5,
        recoveryScore: Double = 0.5,
        sleepDebtHours: Double = 0,
        availableMinutes: Int = 480,
        contextNotes: String = "",
        executiveFunctionScore: Int = 50,
        recommendedTaskDifficulty: TaskDifficulty = .medium,
        timestamp: Date = Date(),
        userId: String = ""
    ) {
        self.id = id
        self.energy = energy
        self.energyScore = energyScore
        self.stressScore = stressScore
        self.focusCapacity = focusCapacity
        self.recoveryScore = recoveryScore
        self.sleepDebtHours = sleepDebtHours
        self.availableMinutes = availableMinutes
        self.contextNotes = contextNotes
        self.executiveFunctionScore = executiveFunctionScore
        self.recommendedTaskDifficulty = recommendedTaskDifficulty
        self.timestamp = timestamp
        self.userId = userId
    }
}

/// Daily health summary — aggregated from HealthKit data.
/// Only summaries (not raw data) are synced to Firebase.
public struct HealthSummary: Identifiable, Codable, Sendable {
    public var id: String
    public var date: Date
    
    // Sleep
    public var totalSleepMinutes: Double?
    public var deepSleepMinutes: Double?
    public var remSleepMinutes: Double?
    public var coreSleepMinutes: Double?
    public var awakeMinutes: Double?
    public var sleepQualityScore: Double?   // 0.0 - 1.0
    public var bedtime: Date?
    public var wakeTime: Date?
    
    // Heart
    public var restingHeartRate: Double?
    public var averageHeartRate: Double?
    public var hrvAverage: Double?          // SDNN in ms
    public var hrvTrend: String?            // "improving", "declining", "stable"
    
    // Activity
    public var stepCount: Int?
    public var activeCalories: Double?
    public var exerciseMinutes: Int?
    public var standHours: Int?
    public var workoutCount: Int?
    public var workoutTypes: [String]?
    
    // Other
    public var bloodOxygen: Double?
    public var wristTemperature: Double?
    public var mindfulMinutes: Int?
    public var waterIntakeMl: Double?
    
    // AI-generated
    public var aiInsight: String?
    public var recoveryRecommendation: String?
    
    public var userId: String
    
    public init(
        id: String = UUID().uuidString,
        date: Date = Date(),
        userId: String = ""
    ) {
        self.id = id
        self.date = date
        self.userId = userId
    }
}

/// A semantic memory entry — part of the "AI Memory" system.
/// Stores text with embedding vectors for semantic search.
public struct MemoryEntry: Identifiable, Codable, Sendable {
    public var id: String
    public var content: String
    public var summary: String
    public var lifeArea: LifeArea?
    public var tags: [String]
    public var embeddingVector: [Double]?
    public var sourceType: String          // "task", "inbox", "conversation", "manual"
    public var sourceId: String?
    public var importance: Double           // 0.0 - 1.0
    public var createdAt: Date
    public var lastAccessedAt: Date
    public var accessCount: Int
    public var userId: String
    
    public init(
        id: String = UUID().uuidString,
        content: String,
        summary: String = "",
        lifeArea: LifeArea? = nil,
        tags: [String] = [],
        embeddingVector: [Double]? = nil,
        sourceType: String = "manual",
        sourceId: String? = nil,
        importance: Double = 0.5,
        createdAt: Date = Date(),
        lastAccessedAt: Date = Date(),
        accessCount: Int = 0,
        userId: String = ""
    ) {
        self.id = id
        self.content = content
        self.summary = summary
        self.lifeArea = lifeArea
        self.tags = tags
        self.embeddingVector = embeddingVector
        self.sourceType = sourceType
        self.sourceId = sourceId
        self.importance = importance
        self.createdAt = createdAt
        self.lastAccessedAt = lastAccessedAt
        self.accessCount = accessCount
        self.userId = userId
    }
}

/// Productivity session tracked from the macOS app.
public struct ProductivitySession: Identifiable, Codable, Sendable {
    public var id: String
    public var appName: String
    public var windowTitle: String?
    public var category: ProductivityCategory
    public var durationSeconds: Int
    public var startedAt: Date
    public var endedAt: Date
    public var isIdleTime: Bool
    public var userId: String
    
    public init(
        id: String = UUID().uuidString,
        appName: String,
        windowTitle: String? = nil,
        category: ProductivityCategory = .neutral,
        durationSeconds: Int = 0,
        startedAt: Date = Date(),
        endedAt: Date = Date(),
        isIdleTime: Bool = false,
        userId: String = ""
    ) {
        self.id = id
        self.appName = appName
        self.windowTitle = windowTitle
        self.category = category
        self.durationSeconds = durationSeconds
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.isIdleTime = isIdleTime
        self.userId = userId
    }
}

/// Categories for productivity tracking.
public enum ProductivityCategory: String, Codable, CaseIterable, Sendable {
    case deepWork = "Deep Work"
    case communication = "Communication"
    case planning = "Planning"
    case creative = "Creative"
    case learning = "Learning"
    case entertainment = "Entertainment"
    case social = "Social Media"
    case neutral = "Neutral"
    case idle = "Idle"
}

/// Daily behavioral summary generated by AI from all data sources.
public struct DailySummary: Identifiable, Codable, Sendable {
    public var id: String
    public var date: Date
    public var tasksCompleted: Int
    public var tasksCreated: Int
    public var tasksDeferred: Int
    public var totalFocusMinutes: Int
    public var longestFocusStreak: Int
    public var topLifeAreas: [LifeArea]
    public var averageEnergy: EnergyLevel
    public var executiveFunctionScore: Int
    public var aiNarrativeSummary: String
    public var aiPatternInsights: [String]
    public var aiRecommendationsForTomorrow: [String]
    public var healthSummaryId: String?
    public var userId: String
    public var createdAt: Date
    
    public init(
        id: String = UUID().uuidString,
        date: Date = Date(),
        tasksCompleted: Int = 0,
        tasksCreated: Int = 0,
        tasksDeferred: Int = 0,
        totalFocusMinutes: Int = 0,
        longestFocusStreak: Int = 0,
        topLifeAreas: [LifeArea] = [],
        averageEnergy: EnergyLevel = .moderate,
        executiveFunctionScore: Int = 50,
        aiNarrativeSummary: String = "",
        aiPatternInsights: [String] = [],
        aiRecommendationsForTomorrow: [String] = [],
        healthSummaryId: String? = nil,
        userId: String = "",
        createdAt: Date = Date()
    ) {
        self.id = id
        self.date = date
        self.tasksCompleted = tasksCompleted
        self.tasksCreated = tasksCreated
        self.tasksDeferred = tasksDeferred
        self.totalFocusMinutes = totalFocusMinutes
        self.longestFocusStreak = longestFocusStreak
        self.topLifeAreas = topLifeAreas
        self.averageEnergy = averageEnergy
        self.executiveFunctionScore = executiveFunctionScore
        self.aiNarrativeSummary = aiNarrativeSummary
        self.aiPatternInsights = aiPatternInsights
        self.aiRecommendationsForTomorrow = aiRecommendationsForTomorrow
        self.healthSummaryId = healthSummaryId
        self.userId = userId
        self.createdAt = createdAt
    }
}

/// Energy self-report logged by the user.
public struct EnergyReport: Identifiable, Codable, Sendable {
    public var id: String
    public var energy: EnergyLevel
    public var mood: String?
    public var notes: String?
    public var timestamp: Date
    public var userId: String
    
    public init(
        id: String = UUID().uuidString,
        energy: EnergyLevel,
        mood: String? = nil,
        notes: String? = nil,
        timestamp: Date = Date(),
        userId: String = ""
    ) {
        self.id = id
        self.energy = energy
        self.mood = mood
        self.notes = notes
        self.timestamp = timestamp
        self.userId = userId
    }
}

/// User profile with preferences and settings.
/// API keys must never live on this Codable surface — use SecretStore / Keychain only.
public struct UserProfile: Identifiable, Codable, Sendable {
    public var id: String
    public var displayName: String
    public var email: String?
    public var peakEnergyStartHour: Int     // e.g., 9 (9 AM)
    public var peakEnergyEndHour: Int       // e.g., 12 (noon)
    public var targetSleepHours: Double     // e.g., 8.0
    public var workStartHour: Int
    public var workEndHour: Int
    public var medications: [MedicationSchedule]
    public var preferredTaskDuration: Int   // in minutes, default 5
    public var enableHealthTracking: Bool
    /// Deprecated leftover — never encoded. Kept so call sites compile; always nil after decode.
    public var geminiApiKey: String?
    public var createdAt: Date
    public var updatedAt: Date

    private enum CodingKeys: String, CodingKey {
        case id, displayName, email
        case peakEnergyStartHour, peakEnergyEndHour, targetSleepHours
        case workStartHour, workEndHour, medications
        case preferredTaskDuration, enableHealthTracking
        case createdAt, updatedAt
    }
    
    public init(
        id: String = UUID().uuidString,
        displayName: String = "User",
        email: String? = nil,
        peakEnergyStartHour: Int = 9,
        peakEnergyEndHour: Int = 12,
        targetSleepHours: Double = 8.0,
        workStartHour: Int = 9,
        workEndHour: Int = 18,
        medications: [MedicationSchedule] = [],
        preferredTaskDuration: Int = 5,
        enableHealthTracking: Bool = true,
        geminiApiKey: String? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.displayName = displayName
        self.email = email
        self.peakEnergyStartHour = peakEnergyStartHour
        self.peakEnergyEndHour = peakEnergyEndHour
        self.targetSleepHours = targetSleepHours
        self.workStartHour = workStartHour
        self.workEndHour = workEndHour
        self.medications = medications
        self.preferredTaskDuration = preferredTaskDuration
        self.enableHealthTracking = enableHealthTracking
        self.geminiApiKey = nil
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        _ = geminiApiKey
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        displayName = try c.decode(String.self, forKey: .displayName)
        email = try c.decodeIfPresent(String.self, forKey: .email)
        peakEnergyStartHour = try c.decode(Int.self, forKey: .peakEnergyStartHour)
        peakEnergyEndHour = try c.decode(Int.self, forKey: .peakEnergyEndHour)
        targetSleepHours = try c.decode(Double.self, forKey: .targetSleepHours)
        workStartHour = try c.decode(Int.self, forKey: .workStartHour)
        workEndHour = try c.decode(Int.self, forKey: .workEndHour)
        medications = try c.decodeIfPresent([MedicationSchedule].self, forKey: .medications) ?? []
        preferredTaskDuration = try c.decodeIfPresent(Int.self, forKey: .preferredTaskDuration) ?? 5
        enableHealthTracking = try c.decodeIfPresent(Bool.self, forKey: .enableHealthTracking) ?? true
        createdAt = try c.decodeIfPresent(Date.self, forKey: .createdAt) ?? Date()
        updatedAt = try c.decodeIfPresent(Date.self, forKey: .updatedAt) ?? Date()
        geminiApiKey = nil
    }

    public func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(id, forKey: .id)
        try c.encode(displayName, forKey: .displayName)
        try c.encodeIfPresent(email, forKey: .email)
        try c.encode(peakEnergyStartHour, forKey: .peakEnergyStartHour)
        try c.encode(peakEnergyEndHour, forKey: .peakEnergyEndHour)
        try c.encode(targetSleepHours, forKey: .targetSleepHours)
        try c.encode(workStartHour, forKey: .workStartHour)
        try c.encode(workEndHour, forKey: .workEndHour)
        try c.encode(medications, forKey: .medications)
        try c.encode(preferredTaskDuration, forKey: .preferredTaskDuration)
        try c.encode(enableHealthTracking, forKey: .enableHealthTracking)
        try c.encode(createdAt, forKey: .createdAt)
        try c.encode(updatedAt, forKey: .updatedAt)
    }
}

/// Medication schedule for tracking adherence.
public struct MedicationSchedule: Identifiable, Codable, Sendable, Hashable {
    public var id: String
    public var name: String
    public var dosage: String
    public var scheduledTimes: [Date]
    public var daysOfWeek: [Int]           // 1=Sunday, 7=Saturday
    public var notes: String
    public var isActive: Bool
    
    public init(
        id: String = UUID().uuidString,
        name: String,
        dosage: String = "",
        scheduledTimes: [Date] = [],
        daysOfWeek: [Int] = [1, 2, 3, 4, 5, 6, 7],
        notes: String = "",
        isActive: Bool = true
    ) {
        self.id = id
        self.name = name
        self.dosage = dosage
        self.scheduledTimes = scheduledTimes
        self.daysOfWeek = daysOfWeek
        self.notes = notes
        self.isActive = isActive
    }
}
