import Foundation
import XCTest

/// Writes XCUI screenshots into `screenshots/ux-agent/` for Cursor UI/UX agent review.
enum UXReviewCapture {
    /// Primary destinations the agent should open first.
    /// Capture is last so its sheet does not block Brain / You / Settings shots.
    static let coreScreens: [(id: String, title: String, notes: String)] = [
        ("S02", "Briefing", "First viewport, scroll hint, continue CTA, tab bar"),
        ("S05", "Today", "Hero / priorities, timeline density, Start now sizing"),
        ("S19", "Brain", "Ask Brain / orb, density"),
        ("S42", "You", "Profile / settings entry"),
        ("S21", "Settings", "Settings stack if reachable"),
        ("S04", "Tab bar", "Capture FAB, label fit, home-indicator flush"),
        ("S39", "Capture", "Composer sheet, mic/save, morph from tab"),
        ("S14", "Task list", "All tasks from Today"),
    ]

    static var exportEnabled: Bool {
        ProcessInfo.processInfo.arguments.contains("-ExportUXReview")
            || ProcessInfo.processInfo.environment["LOOKAFTER_EXPORT_UX_REVIEW"] == "1"
    }

    static func runDirectory(stamp: String) -> String {
        let root = EvidenceWriter.discoverRepoRoot()
        return (root as NSString).appendingPathComponent("screenshots/ux-agent/\(stamp)")
    }

    static func latestDirectory() -> String {
        let root = EvidenceWriter.discoverRepoRoot()
        return (root as NSString).appendingPathComponent("screenshots/ux-agent/latest")
    }

    /// Removes previous PNGs/crops so a failed Auth run cannot poison the next review.
    static func resetLatestDirectory() {
        let latest = latestDirectory()
        let crops = (latest as NSString)
            .deletingLastPathComponent
            .appending("/crops")
        for path in [latest, crops] {
            if FileManager.default.fileExists(atPath: path) {
                try? FileManager.default.removeItem(atPath: path)
            }
            try? FileManager.default.createDirectory(atPath: path, withIntermediateDirectories: true)
        }
    }

    /// Saves PNG to `latest/` and the stamped run folder. Returns absolute path in `latest/`.
    @discardableResult
    static func save(
        _ screenshot: XCUIScreenshot,
        screenId: String,
        title: String,
        reached: Bool,
        stamp: String,
        extraNotes: String = ""
    ) -> String {
        let data = screenshot.pngRepresentation
        let fileName = "\(screenId)_\(slug(title)).png"
        let latestDir = latestDirectory()
        let runDir = runDirectory(stamp: stamp)
        for dir in [latestDir, runDir] {
            try? FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
            let path = (dir as NSString).appendingPathComponent(fileName)
            try? data.write(to: URL(fileURLWithPath: path))
        }
        appendManifestLine(
            stamp: stamp,
            screenId: screenId,
            title: title,
            fileName: fileName,
            reached: reached,
            extraNotes: extraNotes
        )
        return (latestDir as NSString).appendingPathComponent(fileName)
    }

    static func writeManifestHeader(stamp: String) {
        let header = """
        # UX agent screenshot run — \(stamp)

        Generated by `LookAfterSnapshotTests` / `UXAgentCaptureUITests` with `-ExportUXReview`.
        Point the UI/UX agent at `screenshots/ux-agent/latest/` (or this run folder).

        | ID | Screen | File | Reached | Notes |
        |----|--------|------|---------|-------|

        """
        for dir in [latestDirectory(), runDirectory(stamp: stamp)] {
            try? FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
            let path = (dir as NSString).appendingPathComponent("MANIFEST.md")
            try? header.write(toFile: path, atomically: true, encoding: .utf8)
        }
    }

    private static func appendManifestLine(
        stamp: String,
        screenId: String,
        title: String,
        fileName: String,
        reached: Bool,
        extraNotes: String
    ) {
        let line = "| \(screenId) | \(title) | `\(fileName)` | \(reached ? "yes" : "no") | \(extraNotes) |\n"
        for dir in [latestDirectory(), runDirectory(stamp: stamp)] {
            let path = (dir as NSString).appendingPathComponent("MANIFEST.md")
            if FileManager.default.fileExists(atPath: path),
               let handle = FileHandle(forWritingAtPath: path) {
                defer { try? handle.close() }
                handle.seekToEndOfFile()
                if let data = line.data(using: .utf8) {
                    handle.write(data)
                }
            } else {
                let header = """
                # UX agent screenshot run — \(stamp)

                | ID | Screen | File | Reached | Notes |
                |----|--------|------|---------|-------|
                """
                try? (header + line).write(toFile: path, atomically: true, encoding: .utf8)
            }
        }
    }

    private static func slug(_ title: String) -> String {
        title
            .lowercased()
            .replacingOccurrences(of: " ", with: "-")
            .replacingOccurrences(of: "/", with: "-")
    }
}
